//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonado()
        {
            this.EmpleadoPresupuestoes = new HashSet<EmpleadoPresupuesto>();
            this.Pago_Informal = new HashSet<Pago_Informal>();
            this.Proyecto_detalle = new HashSet<Proyecto_detalle>();
            this.ProyectoDetalleSinPresupuestoes = new HashSet<ProyectoDetalleSinPresupuesto>();
            this.Pagoes = new HashSet<Pago>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string TipoEmpleado { get; set; }
        public string Fecha_inscripcion { get; set; }
        public string Telefono { get; set; }
        public string Lugar { get; set; }
        public int Estado { get; set; }
        public Nullable<int> IdTipoEmpleado { get; set; }
    
        public virtual TipoEmpleado TipoEmpleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoPresupuesto> EmpleadoPresupuestoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_Informal> Pago_Informal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto_detalle> Proyecto_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoDetalleSinPresupuesto> ProyectoDetalleSinPresupuestoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagoes { get; set; }
    }
}
