//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_pago_informal
    {
        public int Id { get; set; }
        public string Razon { get; set; }
        public Nullable<int> CajaChica { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Periodo_pago { get; set; }
        public Nullable<int> IdPagoInformal { get; set; }
    
        public virtual Pago_Informal Pago_Informal { get; set; }
    }
}
