//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public byte[] Logo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string RNC { get; set; }
        public string Web { get; set; }
        public string Correo { get; set; }
    }
}
