//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_pago_informal
    {
        public int Id { get; set; }
        public string Razon { get; set; }
        public Nullable<int> CajaChica { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Periodo_pago { get; set; }
        public Nullable<int> IdPagoInformal { get; set; }
    
        public virtual Pago_Informal Pago_Informal { get; set; }
    }
}
