//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoPresupuesto
    {
        public int Id { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        public virtual Abonado Abonado { get; set; }
        public virtual Presupuesto Presupuesto { get; set; }
    }
}
