//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiale
    {
        public int IdMaterial { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PrecioUnidad { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaActualizada { get; set; }
    
        public virtual Vendedore Vendedore { get; set; }
    }
}
