//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiale
    {
        public int IdMaterial { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PrecioUnidad { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaActualizada { get; set; }
    
        public virtual Vendedore Vendedore { get; set; }
    }
}
