//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obra_detalle
    {
        public int id { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Direccion { get; set; }
    
        public virtual Presupuesto Presupuesto { get; set; }
    }
}
