//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoDetalle
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdPagoMaestro { get; set; }
    
        public virtual PagoMaestro PagoMaestro { get; set; }
        public virtual Proyecto_detalle Proyecto_detalle { get; set; }
    }
}
