//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_Informal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago_Informal()
        {
            this.Comprobante_pago_informal = new HashSet<Comprobante_pago_informal>();
        }
    
        public int Id { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<int> IdAbonado { get; set; }
    
        public virtual Abonado Abonado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante_pago_informal> Comprobante_pago_informal { get; set; }
    }
}
