//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_Informal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago_Informal()
        {
            this.Comprobante_pago_informal = new HashSet<Comprobante_pago_informal>();
        }
    
        public int Id { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<int> IdAbonado { get; set; }
    
        public virtual Abonado Abonado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante_pago_informal> Comprobante_pago_informal { get; set; }
    }
}
