//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuesto()
        {
            this.EmpleadoPresupuestoes = new HashSet<EmpleadoPresupuesto>();
            this.Materiales_detalle = new HashSet<Materiales_detalle>();
            this.Obra_detalle = new HashSet<Obra_detalle>();
            this.ProyectoConPresupuestoes = new HashSet<ProyectoConPresupuesto>();
        }
    
        public int IdPresupuestos { get; set; }
        public string FechaCreacion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> TotalGeneral { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoPresupuesto> EmpleadoPresupuestoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiales_detalle> Materiales_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obra_detalle> Obra_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoConPresupuesto> ProyectoConPresupuestoes { get; set; }
    }
}
