//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoConPresupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProyectoConPresupuesto()
        {
            this.PagoMaestroes = new HashSet<PagoMaestro>();
            this.Proyecto_detalle = new HashSet<Proyecto_detalle>();
        }
    
        public int IdProyecto { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> CantidadPresupuestada { get; set; }
        public string FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoMaestro> PagoMaestroes { get; set; }
        public virtual Presupuesto Presupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto_detalle> Proyecto_detalle { get; set; }
    }
}
