//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto_detalle()
        {
            this.PagoDetalles = new HashSet<PagoDetalle>();
        }
    
        public int IdProyectoDetalle { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdProyecto { get; set; }
    
        public virtual Abonado Abonado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoDetalle> PagoDetalles { get; set; }
        public virtual ProyectoConPresupuesto ProyectoConPresupuesto { get; set; }
    }
}
