//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Usuario1 { get; set; }
        public string Pass { get; set; }
        public string Pass2 { get; set; }
        public int Id { get; set; }
    }
}
