//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CabeceraAmbos
    {
        public int IdPresupuestos { get; set; }
        public string Comentario { get; set; }
        public string Fecha { get; set; }
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> TotalMateriales { get; set; }
        public Nullable<int> TotalObra { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int IdListadoPresupuesto { get; set; }
    }
}
