//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_ListadoPresupuestoObra
    {
        public string Descripcion { get; set; }
        public Nullable<int> Total { get; set; }
        public string Nombre { get; set; }
        public string TipoCliente { get; set; }
        public string Telefono { get; set; }
        public string FechaCreacion { get; set; }
        public int IdPresupuestos { get; set; }
        public string Direccion { get; set; }
    }
}
