//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_ListadoPresupuestoObra
    {
        public string Descripcion { get; set; }
        public Nullable<int> Total { get; set; }
        public string Nombre { get; set; }
        public string TipoCliente { get; set; }
        public string Telefono { get; set; }
        public string FechaCreacion { get; set; }
        public int IdPresupuestos { get; set; }
        public string Direccion { get; set; }
    }
}
